# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
#  swiftlint:
#    docker:
#      - image: dantoml/swiftlint:latest
#    steps:
#      - checkout
#      - run: swiftlint lint --reporter junit | tee result.xml
#      - store_artifacts:
#          path: result.xml
#      - store_test_results:
#            path: result.xml
  build-and-test:
    macos:
      xcode: "11.2.1"

    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: pod install
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: GoBanka
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
  bump-build:
    macos:
      xcode: "11.2.1"
    environment:
      - LC_ALL: "en_US.UTF-8"
      - LANG: "en_US.UTF-8"
    steps:
      - checkout
      - run:
          name: Installing gem dependencies
          command: bundle install
      - add_ssh_keys:
          fingerprints:
            - "56:cf:26:1e:ad:fe:16:6a:57:bb:de:67:49:2a:64:93"
      - run:
          name: Bump the build number and commit
          command: bundle exec fastlane bump
  deploy-beta:
    macos:
      xcode: "11.2.1"
    environment:
      - LC_ALL: "en_US.UTF-8"
      - LANG: "en_US.UTF-8"
    steps:
      - checkout
      - run:
          name: Installing gem dependencies
          command: bundle install
      - add_ssh_keys:
          fingerprints:
            - "33:22:88:fb:98:ee:5c:4e:12:40:fd:ad:a7:34:03:99"
      - run:
          name: Deploy new build to TestFlight
          command: bundle exec fastlane submit_to_testflight
          
workflows:
  version: 2
  build-test-lint:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - bump-build:
          requires:
            - build-and-test
          filters:
            branches:
              only: staging
            tags:
              only: /.*/
      - deploy-beta:
          requires:
            - build-and-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^builds.*/
