# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # before all do |lane|
  #   setup_circle_ci
  # end

  desc "Bump and tag version"
  lane :bump do
    ensure_git_status_clean
    bump_message = "Bump build number."
    
    # If our latest commit isn't a build bump, then bump the build.
    build_is_already_bumped = last_git_commit[:message].include? bump_message
    next if build_is_already_bumped
    increment_build_number
    commit_version_bump(
      message: bump_message,
      xcodeproj: "GoBanka.xcodeproj"
    )
    add_git_tag
    push_to_git_remote
  end
  
  desc "Submit latest versioned build to testflight"
  lane :submit_to_testflight do |options|
    # 1. Do some math to get build tags
    build_number = get_build_number(xcodeproj: "GoBanka.xcodeproj")
    last_build_number = build_number.to_i - 1
    build_tag = "builds/iosbump/" + build_number
    last_build_tag = "builds/iosbump/" + last_build_number.to_s
    
    # 2. Generate a change log
    comments = changelog_from_git_commits(
        between: [last_build_tag, build_tag],
        pretty: "- %s",
        date_format: "short",
        match_lightweight_tag: false,
        merge_commit_filtering: "exclude_merges"
    )
    
    # 3. Build the app
    match(type: "appstore", readonly: true, skip_docs: true)
    target_scheme = options[:scheme] || "GoBanka-Debug-Development"
    build_app(scheme: target_scheme)
    
    # 4. Upload it to testflight
    groups = options[:groups] || "All Builds"
    upload_to_testflight(
      changelog: comments,
      distribute_external: true,
      groups: groups
    )
  end
end
